name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Выкачиваем репозиторий
      - uses: actions/checkout@v3

      # Настраиваем Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Запускаем Selenoid
      - uses: Xotabu4/selenoid-github-action@v2

      # Запускаем тесты
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      # Скачиваем историю тестов
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      # Генерируем отчет
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      # Публикуем отчет
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish_branch: gh-pages
          publish_dir: allure-history
